### ISSUE TITLE
How to subscribe to websocket onStockTrades and onStockQuotes

### ISSUE THREAD

**Issue by nodesocket** [alpacahq/alpaca-trade-api-js#10]
I am not fully understanding how to use:

```
websocket.onStockTrades(function(data)): Register callback function for the channel 'T.*'.
websocket.onStockQuotes(function(data)): Register callback function for the channel 'Q.*'.
websocket.onStockAggSec(function(data)): Register callback function for the channel 'A.*'.
websocket.onStockAggMin(function(data)): Register callback function for the channel 'AM.*'.
```

Do these require a 3rd party account at [Polygon](https://polygon.io/)? Can we get some more detailed examples?

**Comment by nodesocket** [comment]
I am getting a strange error:

```shell
MacBook-Pro ➜  alpaca-trade node index.js
2018-12-06T04:36:50.649Z [debug] websocket state changed to connecting
2018-12-06T04:36:50.649Z [debug] websocket state changed to authenticating
2018-12-06T04:36:50.649Z [debug] websocket state changed to connected
2018-12-06T04:36:50.649Z [info] connected to websocket
{ NatsError: 'Authorization Violation'
    at Client.processErr (/Users/justin/Sites/alpaca-trade/node_modules/nats/lib/nats.js:1114:28)
    at Client.processInbound (/Users/justin/Sites/alpaca-trade/node_modules/nats/lib/nats.js:859:28)
    at Socket.<anonymous> (/Users/justin/Sites/alpaca-trade/node_modules/nats/lib/nats.js:529:16)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  name: 'NatsError',
  message: '\'Authorization Violation\'',
  code: 'NATS_PROTOCOL_ERR',
  chainedError: undefined }
```

I verified that I am passing a correct `keyId` and `secretKey`.

**Comment by faridelnasire** [comment]
Ran into the exact same error yesterday. It worked a couple minutes before, then without me changing my code it just started returning those errors.

**Comment by ChemicalRocketeer** [comment]
Currently to access polygon data it is required that you have opened a brokerage account. This works on my account. If you have a brokerage account and are seeing this issue then it is indeed a problem.

We are working on adding trade and quote streaming to the Alpaca data api, so you should be able to stream that data soon without requiring a brokerage account.

The streaming endpoints are definitely not well documented right now (not documented at all really) and we are planning on improving this.

**Comment by nodesocket** [comment]
@ChemicalRocketeer thanks for the reply. So, is there anyway without streaming, to get real-time quote prices/volume?

**Comment by ChemicalRocketeer** [comment]
Unfortunately not, until more data api features are available. Creating a brokerage account with Alpaca should be a pretty easy fix in the meantime though, and should make the above code start working.

**Comment by ChemicalRocketeer** [comment]
You might be able to get what you want using the `getBars()` function also.

**Comment by sopko16** [comment]
Hey @suddjian , does this still not work? I tested this before, and I do not see it working so I wanted to ask:

![image](https://user-images.githubusercontent.com/6151913/62324559-72afbc80-b46f-11e9-9ab9-f21c4ea542a6.png)

I'm trying to get some kind of streaming data. 

I've been getting it with this, and hit the limits often when I fetch any more rapidly than ~1000ms:
![image](https://user-images.githubusercontent.com/6151913/62324680-a68ae200-b46f-11e9-8a36-56c501da1cc1.png)

**Comment by suddjian** [comment]
I'm afraid I can't answer that, I'm not involved with this project anymore. @umitanuki?

**Comment by JoeOsterfeld** [comment]
For those using node, you simply have to call `client.connect()`. I had the same issue, then after calling this function, the socket is working as expected. This is not in the API documentation.
