### ISSUE TITLE
How to get today' listed stocks list ?

### ISSUE THREAD

**Issue by kulveersingh** [alpacahq/alpaca-trade-api-js#102]
How to get today's (last 24 hours ) newly listed stocks list?

**Comment by shlomikushchi** [comment]
Hi, I don't think it's possible through the alpaca api. this is what the asset object holds:
![image](https://user-images.githubusercontent.com/7924802/103369663-66e87f80-4ad3-11eb-8bee-ea69e93ba384.png)

try asking that in the slack channels or the alpaca forum, maybe someone will have an idea.
