### ISSUE TITLE
Subscribing to a trade stream; each key meaning

### ISSUE THREAD

**Issue by nodesocket** [alpacahq/alpaca-trade-api-js#11]
I am subscribed to a websocket trade stream for Apple `T.AAPL` and see the following result:

```
{
    "sym": "AAPL",
    "x": 4,
    "p": 169.6019,
    "s": 30,
    "c": [
        37
    ],
    "t": 1549914725299
}
```

What does `x`, `s`, `,c`, mean in this context? Is there a mapping/documentation for these keys?

**Comment by ChemicalRocketeer** [comment]
This subscription is actually using the Polygon API. You can find more information in the [Polygon documentation](https://polygon.io/sockets).

Here's the specific example from that page that relates to your example.

```
{
    "ev": "T",              // Event Type
    "sym": "MSFT",          // Symbol Ticker
    "x": "4",               // Exchange ID
    "p": 114.125,           // Price
    "s": 100,               // Trade Size
    "c": [0, 12],           // Trade Conditions
    "t": 1536036818784      // Trade Timestamp ( Unix MS )
}
```

**Comment by nodesocket** [comment]
Thanks @ChemicalRocketeer, but unfortunately there is no mapping of exchange ID's to exchange names and also what the trade conditions array means. Any ideas?
