### ISSUE TITLE
getBars suddenly limited since this afternoon

### ISSUE THREAD

**Issue by MrMoehner** [alpacahq/alpaca-trade-api-js#110]
Hello, 

since this afternoon, the "limit" property of the getBars() functions seems suddenly to be active. ,
I can only receive a maximum of 1000 Bars as described in the API Documentation. 

Thats not even whole a day in the 1 Minute resolution. How am i supposed to do a proper backtesting now? 
I was running simulations with bars of a whole year, just this morning. 
Please reconsider this decision and think about what it means for the users. There is no use for me for your API, if i cant test the algorithm right. 

Thanks and regards

MRMOEHNER

**Comment by shlomikushchi** [comment]
Hi, 
there are a few ways to work with that:
1. store the data locally (saves time the next time you run)
2. do a for loop and get all the data you need in iterations

having said that, this is just the client side. you should ask these kind of requests here: https://forum.alpaca.markets/c/alpaca/feature-requests/14

**Comment by MrMoehner** [comment]
Hello, 
thanks for your quick response. It was just a bad surprise, since the behavior suddenly changed. I will post this as a feature requests.
**In case anybody else runs in the same problem:**
With the following Solution, i check if the data already exists as file. If not, i build a timespan array with 1000 minutes distance from a given start and end date, get all the data and store them as file.
`    
let channelData = {};
    let datesArray = [];
    const channelString = _.join(rawChannels, ",");
    let endDate = new Date(YOURDATE);
    let startDate = new Date(YOURDATE);
    let barsArray = [];
    // ----------------------Check if File is available-------------------------
    try {
      channelData = JSON.parse(
        fs.readFileSync(
          `YOURFILE.json`,
          "utf8"
        )
      );
    } catch (e) {
      //-----------------Build Array with dates and 1000 minutes difference------------------

      const unique = (value, index, self) => {
        return self.indexOf(value) === index;
      };
      let counter = 0;

      datesArray.push(startDate.toISOString()); // Add initial start Date
      while (startDate < endDate) {
        startDate = addMinutes(startDate, 1000);
        datesArray.push(startDate.toISOString());
      }
      //-----------------Get bars for each timespan------------------

      // Loop over the days and get data
      for (let date of datesArray) {
        counter++;
        counter > datesArray.length ? (counter = datesArray.length) : "";

        let result = await this._alpaca.getBars("1Min", channelString, {
          start: date,
          end: datesArray[counter++],
          limit: 1000
        });
        result["USEYOURSYMBOL".length > 0
          ? barsArray.push(...result["USEYOURSYMBOL"])
          : ""; // only add, if it has values,no values during the night
      }

      // delete duplicates, comparing unix timestamp
      channelData = { ["USEYOURSYMBOL"]: barsArray.filter(unique) };
      //sort ascending, using unix timestamp
      channelData["USEYOURSYMBOL"].sort(
        (a, b) => parseFloat(a.price) - parseFloat(b.price)
      );

      // ----------------------Save File --------------------------------
      fs.writeFileSync(
        `./backtesting/marketValues/${FILENAME.json`,
        JSON.stringify(channelData)
      );

      console.log(
        `File ${tFILENAME created`
      );
    } // Catch

`
