### ISSUE TITLE
unknown API KEY

### ISSUE THREAD

**Issue by csidi90** [alpacahq/alpaca-trade-api-js#117]
I was using the api for many months without a problem but today I always get "unknown API key" errors from my apps using this API. I think Alpaca changed some stuff, can someone tell me what should I do or if this API gets updated according to the new alpaca docs?

**Comment by chenaaron3** [comment]
Are you getting the errors from the market data endpoints? I also got the same error for the bars API, but the accounts endpoints still work. I noticed alpaca came out with a v2 api for the market data. Waiting on #111 to be approved to see if it'll fix the problem.
