### ISSUE TITLE
getOrders not using symbols parameter

### ISSUE THREAD

**Issue by lexmarionB** [alpacahq/alpaca-trade-api-js#127]
The actual getOrders() method is not making use of the `symbols` parameter mentioned in the documentation. This is a problem since the probability of missing orders for particular symbols exist.

**Comment by calxibe** [comment]
I'm also hoping for a fix for this... have maked my own function on the side for this purpose

**Comment by lexmarionB** [comment]
duplicate of #109

**Comment by FossilBlade** [comment]
PR: https://github.com/alpacahq/alpaca-trade-api-js/pull/143
