### ISSUE TITLE
.lastQuote(symbol) returns 0 bid and ask prices

### ISSUE THREAD

**Issue by csidi90** [alpacahq/alpaca-trade-api-js#129]
I just updated my apps to use 2.0 version of this package. Unfortunatly, Im still getting random 0 bid and ask prices using the .lastQuote(symbol) function.

**Comment by lexmarionB** [comment]
That happens if no trade happened prior to calling .lastQuote(symbol) function in a day. Just my experience.

**Comment by noramehesz** [comment]
Please use the dataV2 functions (`getLatestTrade(symbol)`, `getLatestQuote(symbol)`). Now the sdk support the multi symbol version of these functions as well.
