### ISSUE TITLE
NatsError / Authorization Violation

### ISSUE THREAD

**Issue by pmc-sstaehle** [alpacahq/alpaca-trade-api-js#13]
Hi there,
I just played around a little bit with tha Alpaca Library for node.js. When following the given example with connection via websocket, I'm getting the NatsError / Authorization Violation error just after connection established. I think that comes from the subscription to the events / symbols. In another forum I read, that this comes from using alpaca paper (test) account. My question is if this is correct and when yes, why that is the case? Because then I dont understand how to use the api with my demo (paper) account.
Furthermore it would be very much appreciated to have a little more examples based on node.js api.

Thanks!

**Comment by suddjian** [comment]
The Polygon market data api only becomes available once you have funded a brokerage account on Alpaca. After you've funded your account, you can use the Polygon api with both paper and live api keys.

**Comment by pmc-sstaehle** [comment]
Ok, I understood. But can I also use paper trading without funding the account then?

**Comment by suddjian** [comment]
You can use paper trading without funding your account, just not the Polygon api (which includes nats)
