### ISSUE TITLE
NatsError: 'Max Connections Reached. Kicked from server due to newer API connection. This connection was the oldest

### ISSUE THREAD

**Issue by nodesocket** [alpacahq/alpaca-trade-api-js#14]
Getting intermittent errors:

```
{ NatsError: 'Max Connections Reached. Kicked from server due to newer API connection. This connection was the oldest.'
    at Client.processErr (node_modules/nats/lib/nats.js:1359:28)
    at Client.processInbound (node_modules/nats/lib/nats.js:1091:26)
    at Socket.stream.on (node_modules/nats/lib/nats.js:719:14)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  name: 'NatsError',
  message:
   '\'Max Connections Reached. Kicked from server due to newer API connection. This connection was the oldest.\'',
  code: 'NATS_PROTOCOL_ERR',
  chainedError: undefined }
```

I understand it's related to opening more than a websocket single stream, however I would expect this error to propagate through `alpaca.websocket.onError()`, however it does not appear to. In fact I am not sure which event listener this error is coming from.

**Comment by ttt733** [comment]
Polygon was experiencing some issues over the last month, but they seem to have stabilized the service. Is anyone still encountering this error?

**Comment by trobbins1981** [comment]
I sometimes get this error when I make a 2nd websocket connection.  Today, it happened, even though i made a connection from a seperate process with a seperate account.  the first account i connected is using the high-quality polygon data.  The 2nd account was using the lower quality data on a seperate process. when it connected, it caused this error on the 1st socket.
However, when i tested this same scenario 2 days ago, this issue did not happen

**Comment by ttt733** [comment]
I'm going to be switching the stream connection from NATS to Websockets, so this shouldn't be an issue once I'm finished with that.
