### ISSUE TITLE
Really bad api. all full of messy. Really bad. Documentation is not good at all.

### ISSUE THREAD

**Issue by BaiMaoLi** [alpacahq/alpaca-trade-api-js#17]

**Comment by BaiMaoLi** [comment]
Really shit.

**Comment by sahibjotsaggu** [comment]
https://github.com/BaiMaoLi/Restaurant/blob/master/.env

**Comment by ttt733** [comment]
In the future, please be a bit more specific and less vulgar when bring up problems you have with the repository.
