### ISSUE TITLE
Websocket stops receiving data with no status change

### ISSUE THREAD

**Issue by corescan** [alpacahq/alpaca-trade-api-js#173]
1. Connect to websocket v2 with a paid account (polygon: true).
2. Subscribes to trades (on any ticker)
3. Data streams properly for < 2 hours, then abruptly goes silent without any apparent status change.

[edit] When connecting to Alpaca stream directly from cli using `$ wscat` the websocket works as expected. I just streamed trades up from around 1pm to 7.20pm (EST) today.

**Comment by calxibe** [comment]
I have also noticed this change in the last version, hopefully it gets fixed fast.

**Comment by noramehesz** [comment]
Hello, we will investigate this!

**Comment by corescan** [comment]
> Hello, we will investigate this!

Thanks. I've written a simpler websocket class using mostly default options to test with.
`binaryType = 'arraybuffer'`
`"ContentType": "application/json"`

With these settings I am now capturing a regularly occurring disconnect event, which I can use to trigger a reconnect. Still not ideal, but it's better than the socket going silent.
Messaging protocols are not my expertise, so I apologize if any of this information may be irrelevant.
Thanks for your help.

**Comment by noramehesz** [comment]
Hey @corescan, just a question, there is a listener for error events ( `onError()` ), did you use this as well? Hopefully it could help.

**Comment by corescan** [comment]
> Hey @corescan, just a question, there is a listener for error events ( `onError()` ), did you use this as well? Hopefully it could help.

Yes @noramehesz I have been using the error listener as well as the disconnect listener.

**Comment by corescan** [comment]
I will try and find some time today to supply you with a working code sample, in case you're having trouble reproducing this. I am working within a docker container, and it will take me a little time to slim down the project.

**Comment by noramehesz** [comment]
Thank you for your help in the recreating, I try it with your configuration, hope I could experience the same as you.

**Comment by noramehesz** [comment]
In the latest release the SDK was extended with reconnection after not getting any ping from the server. I hope this could prevent from the situations like yours. I close this ticket, if you have something more please open a new one.
