### ISSUE TITLE
Samples are out of date....

### ISSUE THREAD

**Issue by avays** [alpacahq/alpaca-trade-api-js#180]
The function calls for lastQuote, lastTrade, etc. are different in the readme from how they actually need to be called since they have been revised. lastQuote is actually getLastQuote and lastTrade is getLastTrade...

**Comment by SyntaxisCS** [comment]
those functions don't work either. Same error as the ones on the readme. "is not a function" I don't see any way to get prices with this sdk

**Comment by yashwp** [comment]
No update for 9 months

**Comment by noramehesz** [comment]
Hi @avays @SyntaxisCS and @yashwp 
In a recent PR I updated the data API related examples in the read me section. After it gets merged you can take a look and also feel free to contribute and extend it anytime! Just tag me on the PR and I will review it. And for the available functions please take a look on [this](https://github.com/alpacahq/alpaca-trade-api-js/blob/master/lib/alpaca-trade-api.js) file.
