### ISSUE TITLE
insufficient subscription - Error message on basic websocket example

### ISSUE THREAD

**Issue by mustafa-hanif** [alpacahq/alpaca-trade-api-js#188]
I just followed the sample code

And these lines

```
socket.subscribeForQuotes(["AAPL"]);
socket.subscribeForTrades(["ETHUSD"]);
socket.subscribeForBars(["SPY"]);
socket.subscribeForStatuses(["*"]);
```

give an error `insufficient subscription`

I think Alpaca wants us to buy a pro plan, but this should be clear

**Comment by majorsauce** [comment]
I think this is because you want to subscribe to the "sip" feed which is the paid plan.
Try using the "iex" feed instead:

```ts
let stream = new DataStream({
  apiKey: API_KEY,
  secretKey: API_SECRET,
  feed: "iex",
  paper: true,
});
```

**Comment by noramehesz** [comment]
Hello, @majorsauce was right, in the free plan you can not subscribe to `*`.
