### ISSUE TITLE
In getDataV2 - TypeError: items is not iterable

### ISSUE THREAD

**Issue by poster983** [alpacahq/alpaca-trade-api-js#192]
OS: MacOS 12.2
Node: 16
NPM Package Version: 2.12.1

I started getting this error yesterday:
```
/Users/me/Documents/Code/Experiments/alpaca/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/rest_v2.js:115
            for (const item of items) {
                                          ^

TypeError: items is not iterable
    at getDataV2_1 (/Users/me/Documents/Code/Experiments/alpaca/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/rest_v2.js:115:32)
    at getDataV2_1.next (<anonymous>)
    at resume (/Users/me/Documents/Code/Experiments/alpaca/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/rest_v2.js:17:44)
    at fulfill (/Users/me/Documents/Code/Experiments/alpaca/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/rest_v2.js:19:31)
```

it was working fine ~2 days ago and there have been no changes to my code.  

I am accessing the data by using: 
```javascript
const barsIterator = alpaca.getBarsV2("AAPL", {limit: 1, timeframe: "1Min"})
for await(let x of barsIterator) {
      console.log(x)
}
```
Logging `items` reveals it to be `null`

Is this a bug or am I doing something wrong?

**Comment by poster983** [comment]
Nevermind it fixed itself.  No code changes were needed.
Closing.

**Comment by daweedco** [comment]
Up , i have the exact same error i didn't change any code , this is how i get the data : 
const bars = [];
let resp = alpaca.getBarsV2("AAPL", {timeframe: "1Min");
for await (let b of resp) {
    bars.push(b);
}
Error is : 

for (const item of items) {
                               ^

TypeError: items is not iterable
    at getDataV2_1 (/var/www/html/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/rest_v2.js:114:32)

**Comment by daweedco** [comment]
UP !

**Comment by alto9** [comment]
I am also encountering this issue when trying to pull bar data.

**Comment by alto9** [comment]
It appears that this function returns data only when the market is open, that may be why

**Comment by drew887** [comment]
Hey @alto9  sorry for the big delay on this one, but does the latest version of the SDK (2.15.0) solve this issue for you?

**Comment by RossBlakeney** [comment]
Never mind. I misunderstood @alto9 comment.
`getBarsV2` only returns data if the dates passed to it contain open market days. Which makes sense.
I just happened to be passing a closed market day.

All working for me now. Thanks.
