### ISSUE TITLE
AlpacaNews type missing `source` field

### ISSUE THREAD

**Issue by jbadger** [alpacahq/alpaca-trade-api-js#194]
According to the [documentation](https://alpaca.markets/docs/api-references/market-data-api/news-data/realtime/#properties), the news socket should return an articles source as a string but the type is missing.

```js
export interface AlpacaNews {
    ID: number;
    Author: string;
    CreatedAt: string;
    UpdatedAt: string;
    Headline: string;
    Summary: string;
    Content: string;
    Images: Array<NewsImage>;
    URL: string;
    Symbols: Array<string>;
}
```

**Comment by noramehesz** [comment]
Thank you for creating an issue about this, we will investigate, and update the SDK soon!
