### ISSUE TITLE
[Bug]: example long-short.js broken

### ISSUE THREAD

**Issue by cboydstun** [alpacahq/alpaca-trade-api-js#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Needs to be refactored to include `getBarsV2()` function. 
![image](https://user-images.githubusercontent.com/52934303/167171595-ba2dd91b-5f18-4eff-9fd6-47b8fd4c2112.png)

trying to run the example results in `getBars()` is not a function error. 

### Expected Behavior

Should run. =) 

### SDK Version I encountered this issue in

alpaca-trade-api-js

### Steps To Reproduce

```markdown
1. In VS Code
2. Install packages and run `npm start`
3. Error on `getBars()` is not a function
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by 99JS** [comment]
@drew887 @cboydstun, I tried refactoring to but it did not work. Is this the right way to do it?

```
const resp = await this.alpaca.getBarsV2(
              stock, {
                limit: 1, 
                timeframe: '1Min'
              })
```

**Comment by drew887** [comment]
@99JS sorry I no longer work for Alpaca and thus no longer maintain this repo :sweat_smile:. 

Maybe @haxdds or @noramehesz can help you here.

**Comment by 99JS** [comment]
Thank you @drew887 for helping on this.

@haxdds, @noramehesz: I am a new subscriber to Alpaca and would really appreciate an example like this one as a starting point. The script however seems to have some issues.

For the above issue, I think I found the issue in the list of stocks. When removing all stocks except `AAPL` and `TSLA` it seems to work.

However, around line 550 it throws another error `Cannot read properties of undefined (reading 'length')`.

```
          } else {
            const resp = await this.alpaca.getBarsV2(
              stock.name, {
                timeframe: '1Min',
                limit: 2
              })
              console.log('resp[stock.name]: ', resp[stock.name]);
            const l = resp[stock.name].length
            const last_close = resp[stock.name][l - 1].closePrice;
            const first_open = resp[stock.name][0].openPrice;
            stock.pc = (last_close - first_open) / first_open;
          }
```

Would be really appreciated if you could help me fix the Node.js example so I can get started.

Thank you for your support!

**Comment by haxdds** [comment]
Addresses in #227
