### ISSUE TITLE
[Question]: Max number of bars returned from getBarsV2

### ISSUE THREAD

**Issue by taylorcode** [alpacahq/alpaca-trade-api-js#223]
### Question form pre-submit checklist.

- [X] I have searched the existing issues to ensure there isn't already an issue about this question.
- [X] My question has to do with the JS SDK and isn't a general question about the API. (If it is please open your issue [here](https://github.com/alpacahq/Alpaca-API))
- [X] My question isn't about how to do a specific algorithm or asking for trade advice (answers to these are outside the scope of this repo).

### Question

The [rest API documentation](https://alpaca.markets/docs/api-references/market-data-api/stock-pricing-data/historical/) suggests that the maximum `limit` for the number of results in a request for bars is 10000

But I’m finding that getBarsV2 does not appear to enforce this limit and will happily return a response with >100k bars.

Should I follow the rest documentation and limit my requests to return <=10000 bars?

**Comment by noramehesz** [comment]
Hi @taylorcode ,
In one API call the SDK request the max amount of data which is 10000 if your limit is at least this amount. But the SDK handles the paging so you can pass a higher limit to its functions but behind the scenes this limit is respected.
