### ISSUE TITLE
[Bug]: getBarsV2 returns AlpacaBar objects without symbols

### ISSUE THREAD

**Issue by majorsauce** [alpacahq/alpaca-trade-api-js#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Polling bars through the getBarsV2 function will return bars without a "Symbol" field being filled. 

### Expected Behavior

The return type for getBarsV2 is an AsyncGenerator returning `AlpacaBar`, which defines the "Symbol" field as a string, therefor I would expect it to be filled with the symbol requested

### SDK Version I encountered this issue in

2.16.1

### Steps To Reproduce

```markdown
1. Call alpaca.getBarsV2("TSLA", {...})
2. Iterate over the AsyncGenerator
3. Print the resulting AlpacaBar, you will see that no Symbol is shown
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

### Anything else?

Could be easily fixed by adjusting the rest_v2.ts file and in the getBars function change

```
  for await (const bar of bars || []) {
    yield AlpacaBarV2(bar);
  }
```

to 

```
  for await (const bar of bars || []) {
    yield AlpacaBarV2({...bar, Symbol: symbol});
  }
```

I could also raise a pull request if wished

**Comment by noramehesz** [comment]
Hi @majorsauce 
The single symbol endpoint for the stock API returns the bars without the symbol since it would be an unnecessary additional data. You can extend the bars with the symbol you called the endpoint if you wish, or you can use the multi symbol endpoint if you have an array of symbols for which you want to get the bars.
