### ISSUE TITLE
[Bug]: getLatestCryptoQuote is not a function

### ISSUE THREAD

**Issue by smithb1994** [alpacahq/alpaca-trade-api-js#243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The documentation states that there is a "getLatestCryptoQuote" function, but there doesn't seem to be. There is however "getLatestCryptoQuotes" that accepts an array of quotes. 

Either change the documentation to reflect the fact the function doesn't exist, or add the function.

### Expected Behavior

Expected "getLatestCryptoQuote" to exist.

### SDK Version I encountered this issue in

^3.0.1

### Steps To Reproduce

```markdown
Call "getLatestCryptoQuote" and get the error response.
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by noramehesz** [comment]
Hi @smithb1994 ,
The correct function is `getLatestCryptoQuotes`. The API doesn't support single endpoints for the crypto data.
Have a nice day 🌞
