### ISSUE TITLE
[Bug]: DataV2 `pageLimit` not respected when `limit` is not specified

### ISSUE THREAD

**Issue by ccankov** [alpacahq/alpaca-trade-api-js#246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I make a DataV2 request such as `getMultiBarsV2` and specify a `pageLimit` (e.g. 10,000) but omit the `limit`, I see the NodeJS API make multiple requests that return 1,000 results each.

```
> (await AlpacaSdk.getMultiBarsV2(["GOOG"], { timeframe: "1Min", start: "2023-06-01", end: "2023-06-30", feed: "sip", pageLimit: 10000 }));

Making request /v2/stocks/bars
Making request /v2/stocks/bars
Making request /v2/stocks/bars
Making request /v2/stocks/bars
Making request /v2/stocks/bars
Making request /v2/stocks/bars
Making request /v2/stocks/bars
Making request /v2/stocks/bars
Making request /v2/stocks/bars
Making request /v2/stocks/bars
Making request /v2/stocks/bars
Making request /v2/stocks/bars
Making request /v2/stocks/bars

Map(1) {
  'GOOG' => [
    {
      Timestamp: '2023-06-01T08:00:00Z',
      OpenPrice: 123.59,
      HighPrice: 123.6,
      LowPrice: 123.59,
      ClosePrice: 123.6,
      Volume: 1228,
      TradeCount: 36,
      VWAP: 123.577557,
      Symbol: 'GOOG'
    },
    ... 12611 more items
  ]
}
```

### Expected Behavior

I would expect this to make requests that specify the query parameter `limit=10000` (as per Alpaca's API data V2 reference, this controls the page size) and thus return 10,000 results each instead of 1,000 results each.

I can work around this by specifying a large `limit` value (as opposed to 10,000) in order for the API to handle pagination for me automatically and return the full set of results:

```
> (await AlpacaSdk.getMultiBarsV2(["GOOG"], { timeframe: "1Min", start: "2023-06-01", end: "2023-06-30", feed: "sip", limit: Number.POSITIVE_INFINITY, pageLimit: 10000 }));

Making request /v2/stocks/bars
Making request /v2/stocks/bars

Map(1) {
  'GOOG' => [
    {
      Timestamp: '2023-06-01T08:00:00Z',
      OpenPrice: 123.59,
      HighPrice: 123.6,
      LowPrice: 123.59,
      ClosePrice: 123.6,
      Volume: 1228,
      TradeCount: 36,
      VWAP: 123.577557,
      Symbol: 'GOOG'
    },
    ... 12611 more items
  ]
}
```

The above ends up being more efficient in terms of reducing network overhead associated with each separate request, and also reduces the likelihood of hitting Alpaca's 200 requests/min free tier rate limit. The workaround is easy, but the bigger problem is that this bug can go unnoticed. 

### SDK Version I encountered this issue in

"@alpacahq/alpaca-trade-api": "3.0.1"

### Steps To Reproduce

```markdown
1. Make DataV2 request such as `getMultiBarsV2`
2. Specify a value for the `pageLimit` option, but omit the `limit` option
3. Monitor the number of network requests being made (could be as simple as adding a `console.log` in `dataV2HttpRequest`
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

### Anything else?

Looking at the source code, I believe this is an issue with how the `pageLimit` and `limit` options are handled in `rest_v2.ts#getDataV2` and `rest_v2.ts#getQueryLimit`.

**Comment by noramehesz** [comment]
Hi @ccankov 
Thank you for reporting this issue, I already opened a pull request which contains the fix and it will be released soon. 
Have a nice day 🌞

**Comment by tvdaredevil** [comment]
@noramehesz, I'm noticing an issue with both historical bars apis, whereby they respond with the correct limit but provide me with no way to request the next page as page_token is not part of the response.

The API responds like so:

<img width="303" height="204" alt="Image" src="https://github.com/user-attachments/assets/56c613fc-b47c-4e3a-8f27-367ab046e41e" />

This is the generator spawned by `getMultiBarsAsyncV2`, how do we reinvoke getMultiBarsAsyncV2 to get the next page?

**Comment by noramehesz** [comment]
@tvdaredevil 
Hey 👋
If you check the implementation of the `getMultiBarsAsyncV2` it calls [getMultiDataV2](https://github.com/alpacahq/alpaca-trade-api-js/blob/247c407e879ddc8b5282ffd3557157aeff665dcb/lib/resources/datav2/rest_v2.ts#L153) inside which handles the paging for you, that's why it is not returning any info regarding that. 
If you have any additional question feel free to ask!
