### ISSUE TITLE
[Bug]: GetNewsParams->includeContent should be include_content

### ISSUE THREAD

**Issue by adamsbarker** [alpacahq/alpaca-trade-api-js#249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run the following:

getNews({ includeContent: true });

I get the following error message, which is an error message originating from the Alpaca API:

code: 400, message: Unexpected query parameter(s): includeContent

### Expected Behavior

The Alpaca API says the correct parameter is "include_content":

https://alpaca.markets/docs/api-references/market-data-api/news-data/historical/

So line 611 in the "lib/resources/datav2/rest_v2.ts" file needs to be changed from "includeContent" to "include_content".

### SDK Version I encountered this issue in

3.0.1 (latest)

### Steps To Reproduce

```markdown
Refer to behavior above.
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by Dave-Patsy** [comment]
The typescipt for AlpacaNews[] is incorrect as well. I had to just build my own fetch request.
