### ISSUE TITLE
Position liquidation API bug

### ISSUE THREAD

**Issue by kz363** [alpacahq/alpaca-trade-api-js#25]
There's a small bug/typo that was introduced in this PR: https://github.com/alpacahq/alpaca-trade-api-js/pull/23/files

This `Position#closeOne()` function will throw an error if you try to run it:
```
// position.js
function closeOne(symbol) {
  return this.httpRequest('/positions' + symbol, null, null, 'DELETE')
}


// alpaca-trade-api.js 
Alpaca.prototype.closePosition = position.closeOne

...

const alpaca = new Alpaca(...);
alpaca.closePosition('AAPL');
// Unhandled rejection StatusCodeError: 404 - {"code":40410000,"message":"endpoint not found"}
```

This is because `closeOne` is missing a `/`
```
function closeOne(symbol) {
  return this.httpRequest('/positions/' + symbol, null, null, 'DELETE')
}
```

**Comment by ttt733** [comment]
Great catch; thanks! I was going off of getAll, which seems to work without the slash. DELETE must not be routed the same way. I'll fix the method in our next code release.

**Comment by ttt733** [comment]
Great catch; thanks! I'll be fixing this in our next release.
