### ISSUE TITLE
[Question]: Has getCryptoBars() been replaced by getLatestCryptoBars() ?

### ISSUE THREAD

**Issue by tCooperBrown** [alpacahq/alpaca-trade-api-js#253]
### Question form pre-submit checklist.

- [X] I have searched the existing issues to ensure there isn't already an issue about this question.
- [X] My question has to do with the JS SDK and isn't a general question about the API. (If it is please open your issue [here](https://github.com/alpacahq/Alpaca-API))
- [X] My question isn't about how to do a specific algorithm or asking for trade advice (answers to these are outside the scope of this repo).

### Question

The docs for getCryptoBars() indicates that it takes a symbol as type String and returns a promise of type Async Generator.

However, I can only make `getCryptoBars()` work if I pass it a symbol of type `Array<String>` and it appears to only return a promise of type Map. Are the docs out of date here? Thanks

Usage where I can get it to work:
```
async function cryptoBars() {
  let resp = await alpaca.getCryptoBars(["BTC/USD"], {
    start: "2024-02-20",
    end: "2024-02-21",
    limit: 3,
    timeframe: "30Min",
  });

  return await resp;
}

cryptoBars().then(console.log);
```
Output:
```
Map(1) {
  'BTC/USD' => [
    {
      Close: 51814.71,
      High: 51835.51,
      Low: 51737.9325,
      TradeCount: 0,
      Open: 51755.14,
      Timestamp: '2024-02-20T00:00:00Z',
      Volume: 0,
      VWAP: 0
    },
    {
      Close: 51668.0265,
      High: 51828.2665,
      Low: 51532.6738213395,
      TradeCount: 4,
      Open: 51821,
      Timestamp: '2024-02-20T00:30:00Z',
      Volume: 0.00155384,
      VWAP: 51592.175382
    },
    {
      Close: 51476.0875,
      High: 51724.491,
      Low: 51383.88,
      TradeCount: 3,
      Open: 51658.5165,
      Timestamp: '2024-02-20T01:00:00Z',
      Volume: 0.022060127,
      VWAP: 51508.901565
    }
  ]
}
```

**Comment by noramehesz** [comment]
Hi @tCooperBrown ,
The documentation was outdated but I already opened a PR to update it. Thank you for reporting !
