### ISSUE TITLE
remains is not defined

### ISSUE THREAD

**Issue by sterlinglemon** [alpacahq/alpaca-trade-api-js#26]
There is a Reference not defined exception at: alpaca-trade-api-js/lib/resources/websockets.js Line 172. 

Change 
`remains = Object.keys(this.subscriptionState)`
To
`let remains = Object.keys(this.subscriptionState)`

This fixes the exception, however the client still is subscribed to the given keys after calling the unsubscribe method. All this method seems to do is alter the subscription list but it fails to fully unsubscribe from the given keys.

**Comment by ttt733** [comment]
Thanks for pointing this out. Unsubscription is currently not actually supported by the Alpaca API. I'll be removing this misleading method in our next release.
