### ISSUE TITLE
[Bug]: Documentation Error: optionChain() vs getOptionChain()

### ISSUE THREAD

**Issue by commanderfun** [alpacahq/alpaca-trade-api-js#270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The documentation for Option chain shows the function name as: optionChain() with a single argument (metadata object).

https://docs.alpaca.markets/reference/optionchain

However, v3.1.2 of the API seems to only have a function called: getOptionChain() that works with two arguments like:

```
const Alpaca = require('@alpacahq/alpaca-trade-api');
const config = require("../config");
const mode = 'live';

const alpaca = new Alpaca({
    keyId: config.alpaca[mode].key,
    secretKey: config.alpaca[mode].secret,
    paper: (mode === 'paper'),
});

const getOptionChain = async function() {

    try {
        
        const chain = await alpaca.getOptionChain('SPY', {
            feed: 'indicative',
            limit: '100',
            strike_price_gte: '580',
            strike_price_lte: '585',
            expiration_date: '2024-10-18',
        });

        return chain; 

    } catch (e) {
        return { error: true, message: e.message };     
    }
}
```

### Expected Behavior

Please update the documentation to match.

### SDK Version I encountered this issue in

alpaca-trade-api: v3.1.2

### Steps To Reproduce

```markdown
Try both function names and see that function optionChain() is not defined.
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by noramehesz** [comment]
The `getOptionChain()` is the function, part of the node SDK, what you can use for querying Alpaca's option chain endpoint. There is no `optionChain()` function in the SDK that's why it gives an error. 
The API reference correctly lists the path and query parameters, all of those can be set in the `getOptionChain()` function's parameters. 
I close this issue but feel free to reopen if you need any further clarification.
