### ISSUE TITLE
No account_updates from websocket

### ISSUE THREAD

**Issue by ajostergaard** [alpacahq/alpaca-trade-api-js#39]
No problem getting order_updates but I never get any account_updates. :(

**Comment by ttt733** [comment]
`account_updates` are sent very infrequently, at the moment. They only come when there is an actual status change to your account, and after onboarding, that will happen infrequently. We've been discussing some ways to get some more useful info into that stream, but right now, no updates is generally the expected case.

**Comment by ajostergaard** [comment]
Thanks for the update.

Therefore the correct way to get up to date 'buying power' is to poll /v2/account, right?

In case it helps influence your deliberatioan, a colleague and I both assumed that was one of the primary reasons for streaming account updates.
