### ISSUE TITLE
Dependency on 'fs' package is broken

### ISSUE THREAD

**Issue by colinwong** [alpacahq/alpaca-trade-api-js#49]
Hi. I just installed this package. When I run it on my node server I kept getting this error:

```
This dependency was not found: 
* fs in ./node_modules/@alpacahq/alpaca-trade-api/node_modules/dotenv/lib/main.js, ./node_modules/request/lib/har.js
```

I did this:
```
npm install --save fs
```

But the error still persist because the `fs` package is no longer supported. See `fs@0.0.1-security`.

What am I missing?

**Comment by philgapp** [comment]
Hi Colin, I had this same issue. After a full day of searching for and attempting various fixes the following worked for me (both on a local Node server and on Vercel):

In the root directory I had to create a 'next.config.js' file:

`module.exports = {
    webpack: (config, options) => {
        config.node = {
            // These 3 options were required to resolve errors I was getting, I added them one by one until I had no compilation errors and my page(s) worked normally!
            fs: 'empty',
            net: 'empty',
            tls: 'empty',
        }

        return config
    },
}`

I hope it helps you too!

**Comment by colinwong** [comment]
Ah thanks for the tip. Will look into the webpack configuration!
