### ISSUE TITLE
Fetching using cors-api.js

### ISSUE THREAD

**Issue by philgapp** [alpacahq/alpaca-trade-api-js#50]
Hello all!

I recently started building upon the Long Short example and am getting errors similar to the following for every request:

`Access to fetch at 'https://data.alpaca.markets/v1/bars/minute?symbols=MRO&limit=10' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

I found the cors-api.js file and it does exactly what I believe will solve the problem, using https://cors-anywhere.herokuapp.com as a proxy for the requests. What I can't find is any documentation or examples on how to use this. It doesn't appear to be a configurable variable when instantiating alpaca-trade-api.js, and I'm not quite an experienced enough developer to make this work on my own without a significant amount of time.

Has anyone used this or know of helpful information? There must be something since this implementation is already here!

Much gratitude,
Phillip

**Comment by shlomikushchi** [comment]
Hi Phillip. 
there are 2 long-short examples in this project. 1 runs inside the browser (I am guessing you used that one) and one that runs in node. the one runs in node is the more updated example code. 
try using that one. this is the path to it `examples/long-short.js`
let me know if that works for you.

**Comment by philgapp** [comment]
Thank you Shlomi!

I can confirm this is the file I'm using, but being new to Node and the fact I'm developing an app that is focused on users that have no code knowledge - I have a React page with a button that runs this function (instead of using the example exactly as given, I am instantiating the class after including it in the page and then have a button which onClick calls ls.run(). I'm also trying to modify the example using CancellationTokens or CancellationPromises so a user can click a button on the page to effectively ls.stop(), and use Generators to wrap the class to ensure the algorithm is only able to run once. All this mostly per https://dev.to/chromiumdev/cancellable-async-functions-in-javascript-5gp7). 

Right now it runs, only the quantity error still occurs, and it can run more than once, and implementing the cancellation functionality will take me a couple days or so since I'm learning as I go, and it appears to require a little refactoring of every function in the LongShort class. I think I am running it client side because it is logging to the browser instead of the server console. What is the correct way of allowing a user to run this from the DOM but having it still run in Node and not the client??

Thank you!!

**Comment by shlomikushchi** [comment]
you should run it with node and create a rest api (just a few lines of code) then you could use your onClick() to do http request to the local node server
