### ISSUE TITLE
even the examples don't work...

### ISSUE THREAD

**Issue by tradingbread** [alpacahq/alpaca-trade-api-js#53]
My code:
```
const Alpaca = require('@alpacahq/alpaca-trade-api')

const alpaca = new Alpaca({
  keyId: 'FSKFSF2FR6MKFS6KSDIM',
  secretKey: 'KiCCx5gzVFyfskgj3fdsjkflskd3HJsar32',
  paper: true,
  usePolygon: true,                                                                                                                                                                                         
})

const client = alpaca.websocket

client.onConnect(function() {
  console.log("WS Connected")
  client.subscribe(['trade_updates', 'T.FB', 'Q.AAPL', 'A.FB', 'AM.AAPL'])
})
client.onDisconnect(() => {
  console.log("WS Disconnected")
})
client.onStateChange(newState => {
  console.log(`State changed to ${newState}`)
})

client.onStockQuotes(function(subject, data) {
  console.log(`Stock quotes: ${subject}, ${data}`)
})
client.onStockAggSec(function(subject, data) {
  console.log(`Stock agg sec: ${subject}, ${data}`)
})
client.onStockAggMin(function(subject, data) {
  console.log(`Stock agg min: ${subject}, ${data}`)
})

client.connect()
```

When I run it:
```
State changed to connecting
State changed to authenticating
State changed to disconnected
WS Disconnected
```

And as always, no useful error message.

**Comment by tradingbread** [comment]
Account is also approved and funded

**Comment by kevinsherman** [comment]
Same problem here (though I'm doing pre-funding testing). @tradingbread - you may want to change your keys - especially since your account is funded.

**Comment by shlomikushchi** [comment]
try this example code: https://github.com/alpacahq/alpaca-trade-api-js/blob/master/examples/long-short.js

**Comment by matthewlein** [comment]
@shlomikushchi That example doesn't subscribe to the websocket, which is the issue we're having. Nothing is streaming in.

I downgraded to 1.2.9 and then mine worked fine.

**Comment by matthewlein** [comment]
Also, when resetting the paper account, it stopped working. Reseting my keys and starting again worked fine.

**Comment by shlomikushchi** [comment]
I have updated the code with fixes to the issues you've mentioned.
I also created a new example code to show how to use the websocket API. 
it's called websocket_listener.js
I also added error console log for when we get ws error

**Comment by shlomikushchi** [comment]
you could install it like so: `npm install git+https://github.com/alpacahq/alpaca-trade-api-js.git`
please let me know if there are any other issues

**Comment by shlomikushchi** [comment]
if there aren't any issues with this version I will close this issue. let me know if there are.
