### ISSUE TITLE
algorithms consistently create loss, mean algorithm node.js doesn't run

### ISSUE THREAD

**Issue by AlexLovato** [alpacahq/alpaca-trade-api-js#54]
Unless I'm missing something the long/short algorithm consistently produces loss of value from market open to close.
If anyone can help debug or let me know what I'm doing wrong I can screenshare or share the code I'm using. 
It occurs in both the webpage example and the node.js example of the long/short algorithm. 
The node.js example of the mean averaging algorithm also gets stuck on 'we have 20 bars' so I'm not sure if that algorithm would create gains or not. 
If anyone can help out that'd be great!
Thanks, 
Alex

**Comment by shlomikushchi** [comment]
so these algos are example codes to show how to use the APIs. they are not profitable algorithms.
you should use them to develop your own algos
