### ISSUE TITLE
Request: Polygon Previous Close

### ISSUE THREAD

**Issue by metarama** [alpacahq/alpaca-trade-api-js#64]
Please add polygon previous close to the alpaca interface as polygon data in getHistoricAggregatesV2 does not include the previous day's closing data!

Previous Close is at /v2/aggs/ticker/{ticker}/prev

**Comment by metarama** [comment]
Here's suggestion for the relevant code change.

File alpaca-trade-api-js/lib/resources/polygon.js  line 53 to 58:
const symbolReference = (resource) => function (symbol) {
  const path = '/reference' + (resource ? `/${resource}` : '') + `/${symbol}`
  return this.polygonHttpRequest(path, {}, null, null, 'v2').then((response) => {
    return response.results;
  })
}

changed to pass options parameters as below:
const symbolReference = (resource) => function (symbol, options={}) {
  const path = '/reference' + (resource ? `/${resource}` : '') + `/${symbol}`
  return this.polygonHttpRequest(path, options, null, null, 'v2').then((response) => {
    return response.results;
  })
}

Expose 'Previous Close' as below:
Add line# 68
const prev = symbolReference('prev')

module.exports = {
...
   prev,
}

Finally expose 'prev' method in file alpaca-trade-api-js/lib/alpaca-trade-api.js at line# 123 as
Alpaca.prototype.getPrev = polygon.prev

**Comment by metarama** [comment]
The above approach is good for opening up 'options'. But it will not work for 'prev' as the symbolReference template does not fit with 'prev' URL pattern:  /v2/aggs/ticker/{ticker}/prev

**Comment by shlomikushchi** [comment]
Hi,
sorry for the delayed response.
I just ran this command (it is now `'2020-07-15 10:13:29.374470-04:00'` NY time)

```js
this.alpaca.getHistoricAggregatesV2("AAPL", 1, "day", "2020-07-14", "2020-07-15").then((r) => {
      console.log(r)
    })
```

and this is the response I got:
![image](https://user-images.githubusercontent.com/7924802/87555840-a1de2e80-c6be-11ea-88ef-17ec5a1562d7.png)

which matches yesterday's data (as can be seen here):
![image](https://user-images.githubusercontent.com/7924802/87555917-b6222b80-c6be-11ea-8b1c-ed17fc286ef5.png)

is that what you were trying to achieve?
