### ISSUE TITLE
Documentation Mistake

### ISSUE THREAD

**Issue by JakeBoggs** [alpacahq/alpaca-trade-api-js#65]
[This part](https://github.com/alpacahq/alpaca-trade-api-js#get-account-activities) of the documentation references getActivities, but the correct function name is getAccountActivities.

**Comment by shlomikushchi** [comment]
hi
this is the implementation of the function:
![image](https://user-images.githubusercontent.com/7924802/86518655-9af02a00-be3b-11ea-9114-dbbd1aa73cd8.png)
we are calling `/account/activities`
this is what you meant or are you referring else?

**Comment by JakeBoggs** [comment]
@shlomikushchi, when you call the API, you have to use alpaca.getAccountActivities(), not alpaca.getActivities()

**Comment by shlomikushchi** [comment]
you're right. it points to it:
```py
Alpaca.prototype.getAccountActivities = account.getActivities
```
fixed here: 
https://github.com/alpacahq/alpaca-trade-api-js/pull/71
