### ISSUE TITLE
Dedicated event documentation.

### ISSUE THREAD

**Issue by AqilCont** [alpacahq/alpaca-trade-api-js#67]
I hate the current way you do things, with `.onConnect`, `.onDisconnect`, etc. I am very sure most people would prefer a cleaner, easier to use, events API and documentation used on most other legacy APIs. You can find an example in [Node.js documentation itself](https://nodejs.org/api/http.html#http_class_http_clientrequest), with many of it's native APIs.

**An example:**

### Event `"connect"`

> Added in v1.4

Fired when the websocket connection is successful.

```js
const client = new AlpacaStreamClient();
client.on("connect", () => console.log("Connection successful!")).connect();
```

**Comment by shlomikushchi** [comment]
we have more than one event, so it would never just be `client.on("connect")`
plus, we are wrapping different websockets, and we need to decide which one to use on runtime.
doing it like this can help us do this: 
```js
onStockQuotes(fn) {
    if (this.session.usePolygon) {
      this.polygon.on(EVENT.STOCK_QUOTES, function (subject, data) { fn(subject, data) })
    } else {
      this.on(EVENT.STOCK_QUOTES, function (subject, data) { fn(subject, data) })
    }
  }
```

**Comment by AqilCont** [comment]
> we have more than one event, so it would never just be `client.on("connect")`

I know, this was just an example of what it would look like.

> plus, we are wrapping different websockets, and we need to decide which one to use on runtime.

You can also mention that the events are for both of the websockets, or, an even better method would be to unify those websockets into one and provide something simpler.

> doing it like this can help us do this:
> ```js
> onStockQuotes(fn) {
>     if (this.session.usePolygon) {
>       this.polygon.on(EVENT.STOCK_QUOTES, function (subject, data) { fn(subject, data) })
>     } else {
>       this.on(EVENT.STOCK_QUOTES, function (subject, data) { fn(subject, data) })
>     }
>   }
> ```

Another reason to unify them, as you would just be repeating code and writing a lot more code than needed. If the user specifies that they want to use polygon, then you should use the polygon socket.

**Comment by AqilCont** [comment]
Also, I know this should be a separate issue, but I am pretty sure everyone would love a dedicated, organized wiki for the whole project.

**Comment by umitanuki** [comment]
@AqilCont I am not sure what the scope of the wiki ("the whole project" to me is this whole startup journey itself :) but please feel free to propose your idea. I'm sure others want to see your idea in details and discuss.

**Comment by AqilCont** [comment]
I'm closing this PR since I'm planning to address this issue in the TypeScript version anyways, so there isn't any point in spending time to document anything in the older version.
