### ISSUE TITLE
Cleaner API and less clutter.

### ISSUE THREAD

**Issue by AqilCont** [alpacahq/alpaca-trade-api-js#68]
Is it possible to combine any/all of these events into one event with maybe a type property as a differentiator between them? This is repeated and dirty code that I would like to console.log every time for testing and I keep having to repeat this over and over again. I would greatly appreciate any combination of similar events, as this also straightens my workflow and reduces the digging I have to do through the API.

![image](https://user-images.githubusercontent.com/32044067/86522120-e6e4a400-be26-11ea-8e3f-cb1f47a219d6.png)

**Comment by shlomikushchi** [comment]
Hi, not sure I understand what do you mean "cleaner"
with a single line of code you get different functionalities. you just change the name of the calling function.
what would like to be simpler than that

**Comment by AqilCont** [comment]
Just one event that can do all types of data, separated by type.

**Comment by shlomikushchi** [comment]
these are different events with different structures. it doesn't make much sense to do all in one event

**Comment by umitanuki** [comment]
@AqilCont thanks for the suggestion. We love to discuss over the code, and always welcome your PR!

**Comment by AqilCont** [comment]
We already implemented this type of thing in the typescript version... Maybe take a look at it yourself?
