### ISSUE TITLE
Proper code samples in provided documentation.

### ISSUE THREAD

**Issue by AqilCont** [alpacahq/alpaca-trade-api-js#69]
Please include proper code samples and examples in the documentation! I am not saying that the current method is confusing(which it is, a bit), but to make it cleaner than just random documentation examples that don't apply in the actual coding process.
![image](https://user-images.githubusercontent.com/32044067/86522228-b6056e80-be28-11ea-8a25-4852c05f68d7.png)

An example that could improve cleanliness could be:

### `AlpacaAccount.createOrder(options)`

- `options` : [`<Object>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object) Options containing the details of the order
  - `symbol` : [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) Any valid Ticker symbol. ***(Required)***
  - `qty` : [`<number>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type) Quantity of stocks to purchase. **Default:** 1
  - `side` : [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) To buy or sell this stock, essentially which side the order is executing. Possible values:
    - `"buy"` Buys this stock
    - `"sell"` Sells this stock

Creates and executes a buy or sell order on your account.

#### Example:

```js
const alpaca = await (new Alpaca({
  keyId: 'AKFZXJH121U18SHHDRFO',
  secretKey: 'pnq4YHlpMF3LhfLyOvmdfLmlz6BnASrTPQIASeiU',
  paper: true,
  usePolygon: false
})).getAccount();

alpaca.createOrder({
  symbol: "AAPL", qty: 5, side: "buy"
});
```

> I didn't know what the other options meant so I didn't include them. xd

**Comment by shlomikushchi** [comment]
Hi,
under the examples folder you can see sample code that works and gives a good idea on how to utilize the sdk
https://github.com/alpacahq/alpaca-trade-api-js/tree/master/examples

**Comment by AqilCont** [comment]
But is there any chance you can do it in the docs?

**Comment by shlomikushchi** [comment]
documentation is built in such a way that explains every segment of the code.
this is why there's the sample algos, so a user could refer to the sample code and base their ideas on top of that
