### ISSUE TITLE
Documentation on backtesting algorithms with historical data

### ISSUE THREAD

**Issue by mathew-kurian** [alpacahq/alpaca-trade-api-js#70]
What is the best way to test our algorithms with previous data?

**Comment by AqilCont** [comment]
...you just fetch the data from that date and input it into your algorithm lmao. I thought you would know this if you were creating your own algorithm.

**Comment by shlomikushchi** [comment]
Hi, there is no backtester to the js-sdk. @mathew-kurian

**Comment by mathew-kurian** [comment]
@shlomikushchi Thank you. That would be a great feature imo. Is it in the roadmap?

**Comment by shlomikushchi** [comment]
not currently, no
creating a backtester engine is complicated.
we have under our python packages options for backtesting.
maybe those could help you

**Comment by mathew-kurian** [comment]
@shlomikushchi I understand. Thank you for the prompt response. I'll give those a try
