### ISSUE TITLE
[Deps] Upgrade ws to v7.3

### ISSUE THREAD

**Issue by AndrewBarba** [alpacahq/alpaca-trade-api-js#74]
The sdk is currently using [ws](https://github.com/websockets/ws) v6 which is pretty far behind the latest [v7.3](https://github.com/websockets/ws/releases) which contains a lot of bug fixes:

https://github.com/websockets/ws/releases

**Comment by shlomikushchi** [comment]
thanks. will test it soon

**Comment by shlomikushchi** [comment]
added to v1.3.2
