### ISSUE TITLE
No page_token capability in getAccountActivities() to get next page

### ISSUE THREAD

**Issue by edmundpf** [alpacahq/alpaca-trade-api-js#75]
Some methods in this package have a pageSize parameter, but per the Alpaca API pagination is handled with both page_size and page_token, you submit the last page_token from the prior page to get the next page. In getAccountActivities there is only a page_size parameter, so there appears to be no way to return the next page of results.

https://alpaca.markets/docs/api-documentation/api-v2/account-activities/#tradeactivity-entity

**Comment by edmundpf** [comment]
Added in Pull Request: #76

**Comment by shlomikushchi** [comment]
Hi thanks for your input. version should be updated separately.
added the changes here: https://github.com/alpacahq/alpaca-trade-api-js/pull/78

**Comment by edmundpf** [comment]
> Hi thanks for your input. version should be updated separately.
> added the changes here: #78

My bad force of habit bumping the version, good work thanks!
