### ISSUE TITLE
authentication with auth token

### ISSUE THREAD

**Issue by thedanotto** [alpacahq/alpaca-trade-api-js#77]
hi, was wondering if it was possible to use an auth token for authentication with this package

Instead of this...
```
const alpaca = new Alpaca({
  keyId: <key>,
  secretKey: <secret_key>,
  paper: paperTrading,
  usePolygon: true,
});
```

it'd be something like this...
```
const alpaca = new Alpaca({
  authToken: <auth_token>,
  paper: paperTrading,
  usePolygon: true,
});
```

**Comment by shlomikushchi** [comment]
Hi, check this: https://alpaca.markets/docs/build-apps_services-with-alpaca/oauth-guide/
