### ISSUE TITLE
Bracket Orders: Cannot get nested order status

### ISSUE THREAD

**Issue by immanuelx2** [alpacahq/alpaca-trade-api-js#80]
With an open Bracket order...

`alpaca.getOrders({ status: 'open', limit: 100 })`
I can see the order, but no legs...

`alpaca.getOrders({ status: 'open', limit: 100, nested: true })`
I get no results!

This only seems to happen with Bracket orders, not with OCO.

Is this a known issue / is there a workaround?

**Comment by shlomikushchi** [comment]
Hi.
once a bracket order is filled for the buy order, there are 2 orders left ( take_profit, stop_loss)
at this point they are no longer nested
if your main order is not filled, then it is still nested and you will see all 3 orders.

e.g - this is what I get for filling a bracket order that was never filled:
![image](https://user-images.githubusercontent.com/7924802/89199332-10742500-d5b7-11ea-9bf2-187d60830ef2.png)

and using the code I get:
![image](https://user-images.githubusercontent.com/7924802/89199383-2255c800-d5b7-11ea-96c3-42b6b054be85.png)

under the root order

**Comment by shlomikushchi** [comment]
using this code: 
```js
this.alpaca.getOrders({ status: 'open', limit: 100, nested: true }).then((data) => {
      console.log(data);
    })
```

**Comment by immanuelx2** [comment]
Hi @shlomikushchi 

There seems to be **two potential issues** here:

Before the bracket entry is filled, everything seems to work fine. I can see the order with the following code:
`getOrders({ status: 'open', limit: 100, nested: true })`

However, **once the bracket entry order is filled**...

First issue:
`nested: true` **does not return any results at all**, even though I still have two open orders (take_profit and stop_loss). I understand they are no longer nested, but I'd assume they should still be returned otherwise it looks like I have no open orders at all.

Second issue:
`nested: false`, lets me see the take_profit order, but I **cannot see the stop_loss order** whether I use `nested: true` or not.
