### ISSUE TITLE
I don't quite understand how it works [EXAMPLES]

### ISSUE THREAD

**Issue by Gaserd** [alpacahq/alpaca-trade-api-js#81]
Hey, developers! 
I noticed a few inaccuracies in your examples.
```
client.onConnect(function() {
  console.log("Connected")
  client.subscribe(['alpacadatav1/T.FB', 'Q.AAPL', 'A.FB', 'AM.AAPL'])
})

client.onStockAggMin(function(subject, data) {
  console.log(`Stock agg min: ${subject}, ${data}`)
})
```
This does not work for PaperTrading.
But this code work
```
client.onConnect(function () {
    console.log("Connected")
    client.subscribe(['alpacadatav1/AM.FB'])
})

client.onStockAggMin(function (subject, data) {
    console.log(`Stock agg min: ${subject}, \n${JSON.stringify(data, null, 2)}`)
})
```
And `onStockAggSec` deprecated function? Because I don't see where `A.` type on this https://alpaca.markets/docs/api-documentation/api-v2/market-data/streaming/

**Comment by shlomikushchi** [comment]
Hi Gaserd,
thanks for your input
we have 2 ws services: alpaca and polygon (polygon can only be used in paid accounts)
each support a bit different functionality 
`A.` is only used in polygon
check it here: https://polygon.io/sockets

**Comment by Gaserd** [comment]
> Hi Gaserd,
> thanks for your input
> we have 2 ws services: alpaca and polygon (polygon can only be used in paid accounts)
> each supports a bit different functionality
> `A.` could only be used with polygon
> check it here: https://polygon.io/sockets

Okay, thx
