### ISSUE TITLE
Be able to get orders by filled_at date

### ISSUE THREAD

**Issue by thedanotto** [alpacahq/alpaca-trade-api-js#82]
Hey, I would to have a discussion around a possible enhancement to getting orders. 

```
getOrders({
  status: 'open' | 'closed' | 'all',
  after: Date,
  until: Date,
  limit: number,
  direction: 'asc' | 'desc'
}) => Promise<Order[]>
```

it'd be awesome if we could retrieve orders by `filled`. If an order is filled today, I would like to be able to easily retrieve all filled orders by date.

I found out if a limit order is filled today, but created `n` days ago, the date filter will go based upon when the order was created, not when it was filled.

**Comment by shlomikushchi** [comment]
Hi, feature request for the API (not the package) should be submitted through the Alpaca forum here: https://forum.alpaca.markets/c/alpaca/12
