### ISSUE TITLE
Start and End parameters aren't respected

### ISSUE THREAD

**Issue by kgwebsites** [alpacahq/alpaca-trade-api-js#84]
```
const alpaca = new Alpaca({
    keyId: apiKey,
    secretKey: secret,
    paper: true,
    usePolygon: false
})

    const barset = await alpaca.getBars('1Min', ['AAPL', 'TSLA'], {start:'2020-04-20', end:'2020-04-29'});
    console.log(barset['TSLA'][0]);
```
This results in this response:
```
{
  startEpochTime: 1597426440,
  openPrice: 1651.3,
  highPrice: 1651.3,
  lowPrice: 1649.39,
  closePrice: 1649.39,
  volume: 1035
}
```
`startEpochTime: 1597426440` is Friday, August 14, 2020 5:34:00 PM, which is definitely not between the parameters `start:'2020-04-20', end:'2020-04-29'}`.

Am I missing something here?

**Comment by shlomikushchi** [comment]
Hi,
the proper way to use the getBars function is to use isoformat timezone aware strings as described here: https://alpaca.markets/docs/api-documentation/api-v2/market-data/bars/

I updated the README file to have working examples.
