### ISSUE TITLE
Setting USE_POLYGON = true breaks the JS example script

### ISSUE THREAD

**Issue by vinniejames** [alpacahq/alpaca-trade-api-js#88]
Setting `USE_POLYGON = true` breaks the JavaScript [long-short example script](https://github.com/alpacahq/alpaca-trade-api-js/blob/master/examples/long-short.js).

`this.alpaca.configuration.usePolygon` is returning true, however, the response shape from `.getBars` indicate the Alpaca API is still being called. The script then fails all orders for `NaN`

With USE_POLYGON = true, getBars returns the following:

`let resp = await this.alpaca.getBars('minute', stock.name, { limit: limit })`
```
TWLO {
  startEpochTime: 1600092000,
  openPrice: 228,
  highPrice: 228,
  lowPrice: 228,
  closePrice: 228,
  volume: 724
}
```

No changes have been made other than toggling the Polygon flag
https://github.com/alpacahq/alpaca-trade-api-js/blob/master/examples/long-short.js

**Comment by shlomikushchi** [comment]
Hi, 
sorry for the delay. the issue is fixed here: https://github.com/alpacahq/alpaca-trade-api-js/pull/91
