### ISSUE TITLE
getBars to support adjusted close

### ISSUE THREAD

**Issue by peter-hartmann** [alpacahq/alpaca-trade-api-js#90]
It's unclear how to retrieve adjusted close values using the getBars function, or any other way.

This [python package](https://algotrading101.com/learn/alpaca-trading-api-guide/) seems to support it, so I assume the js package could easily support it as well.

Or what am I missing?

**Comment by shlomikushchi** [comment]
this is the python sdk provided by Alpaca. it's the same api of course:
https://github.com/alpacahq/alpaca-trade-api-python

**Comment by shlomikushchi** [comment]
here's an example of the AAPL stock
![image](https://user-images.githubusercontent.com/7924802/94280054-a001d880-ff55-11ea-9645-b54eb956b239.png)

(I used the python sdk but of course, it should be exactly the same result. lmk if it doesn't)
